db.MarvalMovies.insertMany([
  {
    "Title": "Black Panther",
    "Year": 2018,
    "Runtime": "134 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Ryan Coogler",
    "Writer": "Ryan Coogler, Joe Robert Cole, Stan Lee",
    "Actors": "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o",
    "Plot": "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
    "Language": "English, Swahili, Nama, Xhosa, Korean",
    "Country": "United States",
    "imdbRating": 7.3,
    "imdbVotes": "889,185",
    "imdbID": "tt1825683",
    "BoxOffice": "$700,426,566",
    "Production": "N/A"
  },
  {
    "Title": "Avengers: Infinity War",
    "Year": 2018,
    "Runtime": "149 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Anthony Russo, Joe Russo",
    "Writer": "Christopher Markus, Stephen McFeely, Stan Lee",
    "Actors": "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",
    "Plot": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    "Language": "English",
    "Country": "United States, Norway",
    "imdbRating": 8.4,
    "imdbVotes": "1,313,661",
    "imdbID": "tt4154756",
    "BoxOffice": "$678,815,482",
    "Production": "N/A"
  },
  {
    "Title": "Captain America: The Winter Soldier",
    "Year": 2014,
    "Runtime": "136 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Anthony Russo, Joe Russo",
    "Writer": "Christopher Markus, Stephen McFeely, Joe Simon",
    "Actors": "Chris Evans, Samuel L. Jackson, Scarlett Johansson",
    "Plot": "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.",
    "Language": "English, French",
    "Country": "United States",
    "imdbRating": 7.7,
    "imdbVotes": "947,414",
    "imdbID": "tt1843866",
    "BoxOffice": "$259,766,572",
    "Production": "N/A"
  },
  {
    "Title": "Thor: Ragnarok",
    "Year": 2017,
    "Runtime": "130 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "Taika Waititi",
    "Writer": "Eric Pearson, Craig Kyle, Christopher L. Yost",
    "Actors": "Chris Hemsworth, Tom Hiddleston, Cate Blanchett",
    "Plot": "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",
    "Language": "English",
    "Country": "United States",
    "imdbRating": 7.9,
    "imdbVotes": "869,301",
    "imdbID": "tt3501632",
    "BoxOffice": "$315,058,289",
    "Production": "N/A"
  },
  {
    "Title": "Guardians of the Galaxy",
    "Year": 2014,
    "Runtime": "121 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "James Gunn",
    "Writer": "James Gunn, Nicole Perlman, Dan Abnett",
    "Actors": "Chris Pratt, Vin Diesel, Bradley Cooper",
    "Plot": "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    "Language": "English",
    "Country": "United States, United Kingdom",
    "imdbRating": 8.0,
    "imdbVotes": "1,332,210",
    "imdbID": "tt2015381",
    "BoxOffice": "$333,718,600",
    "Production": "N/A"
  },
  {
    "Title": "Avengers: Endgame",
    "Year": 2019,
    "Runtime": "181 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Anthony Russo, Joe Russo",
    "Writer": "Christopher Markus, Stephen McFeely, Stan Lee",
    "Actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo",
    "Plot": "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    "Language": "English, Japanese, Xhosa, German",
    "Country": "United States",
    "imdbRating": 8.4,
    "imdbVotes": "1,390,337",
    "imdbID": "tt4154796",
    "BoxOffice": "$858,373,000",
    "Production": "N/A"
  },
  {
    "Title": "Captain America: Civil War",
    "Year": 2016,
    "Runtime": "147 min",
    "Genre": "Action, Sci-Fi",
    "Director": "Anthony Russo, Joe Russo",
    "Writer": "Christopher Markus, Stephen McFeely, Joe Simon",
    "Actors": "Chris Evans, Robert Downey Jr., Scarlett Johansson",
    "Plot": "Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
    "Language": "English, German, Xhosa, Russian, Romanian",
    "Country": "United States, Germany, Iceland, United Kingdom",
    "imdbRating": 7.8,
    "imdbVotes": "904,347",
    "imdbID": "tt3498820",
    "BoxOffice": "$408,084,349",
    "Production": "N/A"
  },
  {
    "Title": "Spider-Man: No Way Home",
    "Year": 2021,
    "Runtime": "148 min",
    "Genre": "Action, Adventure, Fantasy",
    "Director": "Jon Watts",
    "Writer": "Chris McKenna, Erik Sommers, Stan Lee",
    "Actors": "Tom Holland, Zendaya, Benedict Cumberbatch",
    "Plot": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.",
    "Language": "English, Tagalog",
    "Country": "United States",
    "imdbRating": 8.2,
    "imdbVotes": "974,763",
    "imdbID": "tt10872600",
    "BoxOffice": "$814,866,759",
    "Production": "N/A"
  },
  {
    "Title": "Shang-Chi and the Legend of the Ten Rings",
    "Year": 2021,
    "Runtime": "132 min",
    "Genre": "Action, Adventure, Fantasy",
    "Director": "Destin Daniel Cretton",
    "Writer": "Dave Callaham, Destin Daniel Cretton, Andrew Lanham",
    "Actors": "Simu Liu, Awkwafina, Tony Leung Chiu-wai",
    "Plot": "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
    "Language": "English, Mandarin",
    "Country": "United States",
    "imdbRating": 7.3,
    "imdbVotes": "469,596",
    "imdbID": "tt9376612",
    "BoxOffice": "$224,543,292",
    "Production": "N/A"
  },
  {
    "Title": "Doctor Strange",
    "Year": 2016,
    "Runtime": "115 min",
    "Genre": "Action, Adventure, Fantasy",
    "Director": "Scott Derrickson",
    "Writer": "Jon Spaihts, Scott Derrickson, C. Robert Cargill",
    "Actors": "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams",
    "Plot": "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
    "Language": "English",
    "Country": "United States, Hong Kong, Nepal",
    "imdbRating": 7.5,
    "imdbVotes": "855,819",
    "imdbID": "tt1211837",
    "BoxOffice": "$232,641,920",
    "Production": "N/A"
  }
,
  {
    "Title": "Spider-Man: Homecoming",
    "Year": 2017,
    "Runtime": "133 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Jon Watts",
    "Writer": "Jonathan Goldstein, John Francis Daley, Jon Watts",
    "Actors": "Tom Holland, Michael Keaton, Robert Downey Jr.",
    "Plot": "Peter Parker tries to stop Adrian 'The Vulture' Toomes from selling weapons made with advanced Chitauri technology while trying to balance his life as an ordinary high school student.",
    "Language": "English, Spanish",
    "Country": "United States",
    "imdbRating": 7.4,
    "imdbVotes": "769,886",
    "imdbID": "tt2250912",
    "BoxOffice": "$334,952,829",
    "Production": "N/A"
  },
  {
    "Title": "Guardians of the Galaxy Vol. 3",
    "Year": 2023,
    "Runtime": "150 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "James Gunn",
    "Writer": "James Gunn, Jim Starlin, Stan Lee",
    "Actors": "Chris Pratt, Chukwudi Iwuji, Bradley Cooper",
    "Plot": "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.",
    "Language": "English, Russian",
    "Country": "United States, New Zealand, France, Canada",
    "imdbRating": 7.9,
    "imdbVotes": "442,838",
    "imdbID": "tt6791350",
    "BoxOffice": "$358,995,815",
    "Production": "N/A"
  },
  {
    "Title": "Ant-Man",
    "Year": 2015,
    "Runtime": "117 min",
    "Genre": "Action, Comedy, Sci-Fi",
    "Director": "Peyton Reed",
    "Writer": "Edgar Wright, Joe Cornish, Adam McKay",
    "Actors": "Paul Rudd, Michael Douglas, Corey Stoll",
    "Plot": "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, pull off a plan that will save the world.",
    "Language": "English",
    "Country": "United States",
    "imdbRating": 7.2,
    "imdbVotes": "761,017",
    "imdbID": "tt0478970",
    "BoxOffice": "$180,202,163",
    "Production": "N/A"
  },
  {
    "Title": "Avengers: Age of Ultron",
    "Year": 2015,
    "Runtime": "141 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Joss Whedon",
    "Writer": "Joss Whedon, Stan Lee, Jack Kirby",
    "Actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo",
    "Plot": "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
    "Language": "English, Korean",
    "Country": "United States, South Korea, Cambodia",
    "imdbRating": 7.3,
    "imdbVotes": "973,147",
    "imdbID": "tt2395427",
    "BoxOffice": "$459,005,868",
    "Production": "N/A"
  },
  {
    "Title": "Spider-Man: Far from Home",
    "Year": 2019,
    "Runtime": "129 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "Jon Watts",
    "Writer": "Chris McKenna, Erik Sommers, Stan Lee",
    "Actors": "Tom Holland, Samuel L. Jackson, Jake Gyllenhaal",
    "Plot": "Peter Parker, the beloved superhero Spider-Man, faces four destructive elemental monsters while on holiday in Europe. Soon, he receives help from Mysterio, a fellow hero with mysterious origins.",
    "Language": "English, Italian, Czech",
    "Country": "United States, Czech Republic, Australia, Canada, Italy",
    "imdbRating": 7.4,
    "imdbVotes": "613,322",
    "imdbID": "tt6320628",
    "BoxOffice": "$391,283,774",
    "Production": "N/A"
  },
  {
    "Title": "Captain Marvel",
    "Year": 2019,
    "Runtime": "123 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Anna Boden, Ryan Fleck",
    "Writer": "Anna Boden, Ryan Fleck, Geneva Robertson-Dworet",
    "Actors": "Brie Larson, Samuel L. Jackson, Ben Mendelsohn",
    "Plot": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
    "Language": "English",
    "Country": "United States, Australia",
    "imdbRating": 6.7,
    "imdbVotes": "642,599",
    "imdbID": "tt4154664",
    "BoxOffice": "$426,829,839",
    "Production": "N/A"
  },
  {
    "Title": "Black Panther: Wakanda Forever",
    "Year": 2022,
    "Runtime": "161 min",
    "Genre": "Action, Adventure, Drama",
    "Director": "Ryan Coogler",
    "Writer": "Ryan Coogler, Joe Robert Cole, Stan Lee",
    "Actors": "Letitia Wright, Lupita Nyong'o, Danai Gurira",
    "Plot": "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
    "Language": "English, Xhosa, Maya, Spanish, Haitian, French",
    "Country": "United States",
    "imdbRating": 6.6,
    "imdbVotes": "341,017",
    "imdbID": "tt9114286",
    "BoxOffice": "$453,829,060",
    "Production": "N/A"
  },
  {
    "Title": "Iron Man",
    "Year": 2008,
    "Runtime": "126 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Jon Favreau",
    "Writer": "Mark Fergus, Hawk Ostby, Art Marcum",
    "Actors": "Robert Downey Jr., Gwyneth Paltrow, Terrence Howard",
    "Plot": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    "Language": "English, Persian, Urdu, Arabic, Kurdish, Hindi, Hungarian",
    "Country": "United States, Canada",
    "imdbRating": 7.9,
    "imdbVotes": "1,190,100",
    "imdbID": "tt0371746",
    "BoxOffice": "$319,034,126",
    "Production": "N/A"
  },
  {
    "Title": "Thor: Love and Thunder",
    "Year": 2022,
    "Runtime": "118 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "Taika Waititi",
    "Writer": "Taika Waititi, Jennifer Kaytin Robinson, Stan Lee",
    "Actors": "Chris Hemsworth, Natalie Portman, Christian Bale",
    "Plot": "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
    "Language": "English",
    "Country": "Australia, United States",
    "imdbRating": 6.1,
    "imdbVotes": "443,961",
    "imdbID": "tt10648342",
    "BoxOffice": "$343,256,830",
    "Production": "N/A"
  },
  {
    "Title": "Eternals",
    "Year": 2021,
    "Runtime": "156 min",
    "Genre": "Action, Adventure, Fantasy",
    "Director": "Chloé Zhao",
    "Writer": "Chloé Zhao, Patrick Burleigh, Ryan Firpo",
    "Actors": "Gemma Chan, Richard Madden, Angelina Jolie",
    "Plot": "The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.",
    "Language": "English, American Sign , Marathi, Assyrian Neo-Aramaic, Spanish, Sumerian, Latin, Sanskrit, Greek, Ancient (to 1453), Arabic",
    "Country": "United States",
    "imdbRating": 6.2,
    "imdbVotes": "415,580",
    "imdbID": "tt9032400",
    "BoxOffice": "$164,870,234",
    "Production": "N/A"
  }
,
  {
    "Title": "Ant-Man and the Wasp",
    "Year": 2018,
    "Runtime": "118 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "Peyton Reed",
    "Writer": "Chris McKenna, Erik Sommers, Paul Rudd",
    "Actors": "Paul Rudd, Evangeline Lilly, Michael Peña",
    "Plot": "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.",
    "Language": "English, Spanish, French",
    "Country": "United States, Canada",
    "imdbRating": 7.0,
    "imdbVotes": "480,241",
    "imdbID": "tt5095030",
    "BoxOffice": "$216,648,740",
    "Production": "N/A"
  },
  {
    "Title": "Thor: The Dark World",
    "Year": 2013,
    "Runtime": "112 min",
    "Genre": "Action, Adventure, Fantasy",
    "Director": "Alan Taylor",
    "Writer": "Christopher L. Yost, Christopher Markus, Stephen McFeely",
    "Actors": "Chris Hemsworth, Natalie Portman, Tom Hiddleston",
    "Plot": "When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous and personal journey that will reunite him with doctor Jane Foster.",
    "Language": "English",
    "Country": "United States, Iceland",
    "imdbRating": 6.7,
    "imdbVotes": "761,960",
    "imdbID": "tt1981115",
    "BoxOffice": "$206,362,140",
    "Production": "N/A"
  },
  {
    "Title": "Iron Man 3",
    "Year": 2013,
    "Runtime": "130 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Shane Black",
    "Writer": "Drew Pearce, Shane Black, Stan Lee",
    "Actors": "Robert Downey Jr., Guy Pearce, Gwyneth Paltrow",
    "Plot": "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
    "Language": "English",
    "Country": "United States",
    "imdbRating": 7.1,
    "imdbVotes": "944,732",
    "imdbID": "tt1300854",
    "BoxOffice": "$409,013,994",
    "Production": "N/A"
  },
  {
    "Title": "Iron Man 2",
    "Year": 2010,
    "Runtime": "124 min",
    "Genre": "Action, Sci-Fi",
    "Director": "Jon Favreau",
    "Writer": "Justin Theroux, Stan Lee, Don Heck",
    "Actors": "Robert Downey Jr., Mickey Rourke, Gwyneth Paltrow",
    "Plot": "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy.",
    "Language": "English, French, Russian",
    "Country": "United States",
    "imdbRating": 6.9,
    "imdbVotes": "914,423",
    "imdbID": "tt1228705",
    "BoxOffice": "$312,433,331",
    "Production": "N/A"
  },
  {
    "Title": "Spider-Man 2",
    "Year": 2004,
    "Runtime": "127 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Sam Raimi",
    "Writer": "Stan Lee, Steve Ditko, Alfred Gough",
    "Actors": "Tobey Maguire, Kirsten Dunst, Alfred Molina",
    "Plot": "Peter Parker is beset with troubles in his failing personal life as he battles a former brilliant scientist named Otto Octavius.",
    "Language": "English, Russian, Chinese",
    "Country": "United States",
    "imdbRating": 7.5,
    "imdbVotes": "759,076",
    "imdbID": "tt0316654",
    "BoxOffice": "$374,337,514",
    "Production": "N/A"
  },
  {
    "Title": "Deadpool & Wolverine",
    "Year": 2024,
    "Runtime": "128 min",
    "Genre": "Action, Adventure, Comedy",
    "Director": "Shawn Levy",
    "Writer": "Ryan Reynolds, Rhett Reese, Paul Wernick",
    "Actors": "Ryan Reynolds, Hugh Jackman, Emma Corrin",
    "Plot": "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
    "Language": "English, French, Spanish",
    "Country": "United States, United Kingdom, New Zealand, Canada",
    "imdbRating": 7.5,
    "imdbVotes": "522,819",
    "imdbID": "tt6263850",
    "BoxOffice": "$636,745,858",
    "Production": "N/A"
  },
  {
    "Title": "The Fantastic Four: First Steps",
    "Year": 2025,
    "Runtime": "114 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Matt Shakman",
    "Writer": "Josh Friedman, Eric Pearson, Jeff Kaplan",
    "Actors": "Pedro Pascal, Vanessa Kirby, Ebon Moss-Bachrach",
    "Plot": "Forced to balance their roles as heroes with the strength of their family bond, the Fantastic Four must defend Earth from a ravenous space god called Galactus and his enigmatic herald, the Silver Surfer.",
    "Language": "English",
    "Country": "United Kingdom, United States, Canada, New Zealand",
    "imdbRating": 7.3,
    "imdbVotes": "134,708",
    "imdbID": "tt10676052",
    "BoxOffice": "$272,903,891",
    "Production": "N/A"
  },
  {
    "Title": "The Incredible Hulk",
    "Year": 2008,
    "Runtime": "112 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Louis Leterrier",
    "Writer": "Zak Penn, Stan Lee, Jack Kirby",
    "Actors": "Edward Norton, Liv Tyler, Tim Roth",
    "Plot": "Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into whenever he loses his temper.",
    "Language": "English, Portuguese, Spanish",
    "Country": "United States, Canada, Japan",
    "imdbRating": 6.6,
    "imdbVotes": "551,341",
    "imdbID": "tt0800080",
    "BoxOffice": "$134,806,913",
    "Production": "N/A"
  },
  {
    "Title": "X-Men: Days of Future Past",
    "Year": 2014,
    "Runtime": "132 min",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Bryan Singer",
    "Writer": "Simon Kinberg, Jane Goldman, Matthew Vaughn",
    "Actors": "Patrick Stewart, Ian McKellen, Hugh Jackman",
    "Plot": "The X-Men send Wolverine to the past in a desperate effort to change history and prevent an event that results in doom for both humans and mutants.",
    "Language": "English, Vietnamese, French, Russian",
    "Country": "United Kingdom, United States, Canada",
    "imdbRating": 7.9,
    "imdbVotes": "776,258",
    "imdbID": "tt1877832",
    "BoxOffice": "$233,921,534",
    "Production": "N/A"
  }
]);
