# Generated by Django 6.0 on 2026-01-12 08:08

import django.core.validators
import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0013_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='barnd',
            field=models.CharField(choices=[('bmw', 'BMW'), ('mercedes benz', 'Mercedes Benz'), ('audi', 'Audi'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jaguar', 'Jaguar'), ('land rover', 'Land Rover'), ('bentley', 'Bentley'), ('bugatti', 'Bugatti'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('honda', 'Honda'), ('toyota', 'Toyota'), ('chevrolet', 'Chevrolet'), ('porsche', 'Porsche')], default='select', max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, max_length=25, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, verbose_name='desc'),
        ),
        migrations.AddField(
            model_name='listing',
            name='engin',
            field=models.CharField(blank=True, max_length=50, verbose_name='Engin Name'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(null=True, upload_to=main.utils.user_list_path),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='milage',
            field=models.CharField(default='0', max_length=200, validators=[django.core.validators.validate_integer], verbose_name='model name'),
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmisstion',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='select', max_length=10),
        ),
    ]
