# Generated by Django 6.0 on 2026-01-12 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_barnd_listing_color_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, max_length=25, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='engin',
            field=models.CharField(blank=True, max_length=50, verbose_name='Engin'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='milage',
            field=models.CharField(default='0', max_length=200, validators=[django.core.validators.validate_integer], verbose_name='MILAGE'),
        ),
    ]
