# Generated by Django 6.0 on 2026-01-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_color_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='transmisstion',
            new_name='transmisson',
        ),
    ]
