# Generated by Django 6.0 on 2026-01-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_1', models.CharField(blank=True, max_length=128)),
                ('Address_2', models.CharField(blank=True, max_length=128)),
                ('City', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
