# Generated by Django 6.0 on 2026-01-08 05:00

import localflavor.in_.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='State',
            field=localflavor.in_.models.INStateField(default='NaN', max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='Zip_Code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN CODE'),
        ),
    ]
