# Generated by Django 6.0 on 2026-01-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
