# Generated by Django 6.0 on 2026-01-08 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_location_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_info', to='users.profile'),
        ),
    ]
