# Generated by Django 6.0 on 2026-01-08 07:50

import django.db.models.deletion
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_location_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Address_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Address_2',
            new_name='address_2',
        ),
        migrations.RemoveField(
            model_name='location',
            name='City',
        ),
        migrations.RemoveField(
            model_name='location',
            name='State',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Zip_Code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.us.models.USStateField(default='NY', max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
