# Generated by Django 6.0 on 2026-01-12 07:49

import django.core.validators
import localflavor.in_.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.validate_integer]),
        ),
    ]
