# Generated by Django 6.0 on 2026-01-12 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_location_state_alter_location_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.validate_integer]),
        ),
    ]
